dist: trusty
language: java
jdk:  oraclejdk8
env: 
  - COVERAGE=0.3 

install:
  - "./gradlew clean jar"

stages:
  - test
  - deploy

jobs:
  - include:
    - stage: test
      name: "checks 1"
      install: skip
      script:
        - ./gradlew -p ./monolithic/ui check
        - ./gradlew -p ./monolithic/service/cart check
        - ./gradlew -p ./monolithic/service/user check
      env:
        COVERAGE = 0.3
    - script:
        - ./gradlew -p ./monolithic/repository/order check
        - ./gradlew -p ./monolithic/repository/cart check
        - ./gradlew -p ./monolithic/repository/product check
        - ./gradlew -p ./monolithic/repository/user check
      name: "Checks 2"
      install: skip
      env:
        COVERAGE = 0.3
       

deploy:
  provider: script
  script: "echo 'WHF'"
  on:
    all_branches: true
